# Generated by Django 3.2.4 on 2021-06-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_images_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
