# Generated by Django 3.2.4 on 2021-07-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_service_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='serviceId',
            new_name='ServiceId',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='status',
        ),
        migrations.AddField(
            model_name='service',
            name='Status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'confirmed'), (2, 'rejected')], default=1),
        ),
    ]
