# Generated by Django 3.2.4 on 2021-07-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20210721_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'confirmed')], default=0),
        ),
    ]
